package pl.sgorski.expense_splitter.features.auth.dto.request;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Pattern;

@Schema(
    name = "Enable Google Authenticator Request",
    description = "Payload used to confirm and enable Google Authenticator (TOTP-based 2FA).")
public record EnableGARequest(
    @Schema(
            description = "6-digit TOTP code generated by Google Authenticator app",
            example = "123456")
        @NotNull
        @Pattern(regexp = "\\d{6}")
        String code) {}
