spring.application.name=expense-splitter
spring.profiles.active=@spring.profiles.active@
spring.threads.virtual.enabled=true
logging.level.pl.sgorski.expense_splitter=DEBUG

# MVC configuration
server.servlet.context-path=/api
spring.mvc.apiversion.default=1.0.0
spring.mvc.apiversion.use.header=X-API-Version
spring.mvc.apiversion.detect-supported=true

# Actuator configuration
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=when_authorized
management.endpoint.health.probes.enabled=true

# Database configuration
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.sql.init.mode=never
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.defer-datasource-initialization=false
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# OAuth2 configuration
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=profile,email
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}

spring.security.oauth2.client.registration.facebook.client-id=${FACEBOOK_CLIENT_ID}
spring.security.oauth2.client.registration.facebook.client-secret=${{FACEBOOK_CLIENT_SECRET}
spring.security.oauth2.client.registration.facebook.scope=email,public_profile
spring.security.oauth2.client.registration.facebook.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
spring.security.oauth2.client.provider.facebook.authorization-uri=https://www.facebook.com/v14.0/dialog/oauth
spring.security.oauth2.client.provider.facebook.token-uri=https://graph.facebook.com/v14.0/oauth/access_token
spring.security.oauth2.client.provider.facebook.user-info-uri=https://graph.facebook.com/me?fields=id,name,email,first_name,last_name

# Swagger configuration
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.filter=true
springdoc.swagger-ui.display-request-duration=true
springdoc.swagger-ui.doc-expansion=none
springdoc.swagger-ui.persist-authorization=true

# Application variables
jwt.secret-key=${JWT_SECRET_KEY}
jwt.expiration-time-in-ms=${JWT_EXPIRATION_TIME_MS:3600000}
refresh-token.expiration-time-in-ms=${REFRESH_TOKEN_EXPIRATION_TIME_MS:604800000}

es.frontend.oauth2-success-url=${ES_FRONTEND_OAUTH2_SUCCESS_URL:http://localhost:3000/login-success}
es.first-admin.email=${ES_FIRST_ADMIN_EMAIL:admin@example.com}
es.first-admin.password=${ES_FIRST_ADMIN_PASSWORD:ES-Admin123#}