springdoc.swagger-ui.enabled=false

# Database configuration
spring.datasource.url=
spring.datasource.username=
spring.datasource.password=
spring.flyway.clean-disabled=false

# OAuth2 dummy config for tests
spring.security.oauth2.client.registration.google.client-id=dummy-client-id
spring.security.oauth2.client.registration.google.client-secret=super-strong-and-long-dummy-client-secret-key
spring.security.oauth2.client.registration.facebook.client-id=dummy-client-id
spring.security.oauth2.client.registration.facebook.client-secret=super-strong-and-long-dummy-client-secret-key

# Email configuration - use mock
spring.mail.host=localhost
spring.mail.port=1025
spring.mail.username=test
spring.mail.password=test

# Disable sentry
sentry.enabled=false

# dummy secrets
jwt.secret-key=super-strong-and-long-dummy-jwt-secret-key
two-factor.encryption-key=jlADbfpIVavJyUFD+zl6IIqCSgCOdh7oQH6dT7XFjQc=

# Test variables
app.test.totp.code=123456
app.test.totp.secret=TEST-SECRET