spring.application.name=expense-splitter

# MVC configuration
server.servlet.context-path=/api
spring.mvc.apiversion.default=1
spring.mvc.apiversion.use.header=X-API-Version
spring.mvc.apiversion.detect-supported=true

# Actuator configuration
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=when_authorized
management.endpoint.health.probes.enabled=true


# Database configuration
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.sql.init.mode=never
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.defer-datasource-initialization=false
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration