spring.datasource.url=jdbc:h2:mem:openapi
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create-drop
spring.sql.init.mode=always
spring.flyway.enabled=false

jwt.secret-key=gTWi8Wum4ejptU3HhOtpB7vugvT3/Cdb2z91WQ2xVh3PYR40b0bJfPrG0QwPH81YXrCYClfubORmhgdZjzElFA==
two-factor.encryption-key=MrAHJ4x7vs5QBrJKYousP2Qq7cwFFi2xdN8M+athvNk=