sentry.enabled=true
sentry.dsn=${SENTRY_DSN}
sentry.send-default-pii=true
sentry.traces-sample-rate=0.2
sentry.environment=${SENTRY_ENVIRONMENT:development}
sentry.release=expense-splitter-api@${SENTRY_RELEASE:undefined}

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true

spring.mail.host=${SPRING_MAIL_HOST}
spring.mail.port=${SPRING_MAIL_PORT}
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}

logging.level.root=INFO
logging.level.pl.sgorski.expense_splitter=INFO
logging.level.org.springframework=WARN
logging.level.org.hibernate=WARN
logging.level.com.zaxxer.hikari=WARN