name: Generate OpenAPI Docs
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate-docs:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: '0'

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '25'
          cache: 'maven'

      - name: Build project and generate OpenAPI
        run: mvn clean verify -Ptest -DskipTests

      - name: Prepare gh-actions branch
        run: |
          git fetch origin
          git worktree add gh-actions-dir origin/gh-actions

      - name: Copy OpenAPI
        run: cp target/openapi.json gh-actions-dir/docs/openapi.json

      - name: Commit and push
        run: |
          cd gh-actions-dir
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          
          if git diff --quiet; then
              echo "No changes to commit"
          else
              git add docs/openapi.json
              git commit -m "docs: Update OpenAPI documentation"
              git push origin HEAD:gh-actions
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
